server:
  port: 5003

telemetry:
  port: 4317
  host: localhost

kafka:
  topics:
    quizz: polyflix.quiz

  client:
    clientId: quizz-backend
    brokers: localhost:29092
  consumer:
    groupId: quizz-consumer
    allowAutoTopicCreation: true

database:
  psql:
    # In case you want to use an URL instead
    # url: postgres://sa_quizz:sa_quizz_pwd@localhost:5433/quizz
    host: localhost
    port: 5433
    username: sa_quizz
    password: sa_quizz_pwd
    database: quizz
    debug: true
