server:
  port: 5000

telemetry:
  port: 4317
  host: localhost

kafka:
  client:
    clientId: todo-backend
    brokers: localhost:9092
  consumer:
    groupId: todo-consumer
    allowAutoTopicCreation: true

database:
  psql:
    # In case you want to use an URL instead
    # url: postgres://sa_video:sa_video_pwd@localhost:5433/video
    host: localhost
    port: 5433
    username: sa_quizz
    password: sa_quizz_pwd
    database: quizz
    debug: true
