version: v2beta1
name: quizz

pipelines:
  dev:
    run: |-
      ensure_pull_secrets --all
      start_dev app
dev:
  app:
    imageSelector: ghcr.io/polyflix/quizz:main
    devImage: ghcr.io/loft-sh/devspace-containers/typescript:18-alpine
    sync:
      - path: ./
        excludePaths:
          - .git/
        uploadExcludePaths:
          - Dockerfile
          - node_modules
          - dist
    terminal:
      command: ./devcontainer.sh
    ports:
      - port: "5003:8080"
